### PR TITLE
remove card-tools requirement

### PR DESCRIPTION
**Pull request by Mariusthvdb**
and added console info version 0.6

### CODE REVIEW

**Comment by iantrich** [comment]
Reverted my merge. Was cleaning up stale custom-cards, and accidently merged this one but looks like @MizterB is still active on it. Will let him take a look.

**Comment by MizterB** [comment]
I cannot get this change to work in my Dev environment (2021.7.0.dev0).  I get the following errors in the console:

Screen Shot 2021-06-12 at 9 12 34 AM

Can you please retest and fix if necessary?  Please submit as a new PR as this one was closed by the merge/revert.

**Comment by MizterB** [comment]
@Mariusthvdb...
On further investigation it is clear that this PR was never tested.  There are numerous issues that would have identified with even a basic test:

1)  Fails at SecondaryInfoEntityRowCard reference shown above
_If I fix this..._
2) It errors out on a check for card-tools, which is still in the code even though this is what you wanted to eliminate
_If I fix this..._
3) Only the Jinja templates work.  The "old" style templates return Promise objects, not a rendered template
_If I fix this...(by trying to awaiting the promise)_
4) The "old" template format render nothing, throwing yet another error...

At this point, you've wasted enough of my time.  This really upsets me, this considering how much you pushed for this, and you couldn't perform the common courtesy of testing.  Even worse, you would have broken the card for anyone else using it.
We are very lucky that @iantrich reverted the merge.

**Comment by Mariusthvdb** [comment]
wow, for someone who has put zero effort in modernizing his own card, (even after having been offered the attention by the author of card-tools himself) you do have a nasty tone here. Even dare stating I wasted enough of your time?? Wow.

Somehow It didnt come to mind to say: hey, something must be wrong because I cant get it to work, please have another look?

this is what it does locally on my side:
Schermafbeelding 2021-06-12 om 17 08 46

with  this config:

```
      - type: custom:secondaryinfo-entity-row
        entity: input_number.home_theater_lux
        secondary_info: >
          Mean living secondary info: {{states('sensor.mean_living_lux')}} lx
```

Safari throws an error now, though before that wasn't there.

there is no card_tools left in the code at all...

anyways, we can do the same now with card-mod:

```
      - entity: input_number.home_theater_lux
        secondary_info: true
        card_mod:
          style:
            hui-generic-entity-row$: |
              .secondary::after {
                content: "Mean living: {{states('sensor.mean_living_lux')}} lx"
                }
```

if you're even remotely interested in the work Thomas and I put into this (which of course you should have done yourself), here the link to [Discord](https://discord.com/channels/330944238910963714/351047592588869643/849620821299429376)

**Comment by MizterB** [comment]
OK, update on this...

First off, I have been in touch with Marius directly to apologize for my earlier response, which was totally inappropriate.  I certainly welcome any help in maintaining this card, and I appreciate his leading the charge in removing this dependency.

As we collaborated, we were able to confirm the source of the problem that I experienced in my testing - the code he shared in the PR was not the latest code that he was testing against.  The latest code has been shared with me, and it does resolve the first couple of issues I experienced in the PR.  The Safari issue he mentioned above still exists, and needs to be worked out before the change can proceed.  We will continue to collaborate via Discord.

@Mariusthvdb - thank you for all your help to date and your willingness to chat with me today.

**Pull request merged**
